import '../models/customer.dart';
import '../models/product.dart';

/// Offline fallback — L/Exempt (GST-free) products only.
class LocalData {
  LocalData._();

  static final List<Product> products = [
    Product(id: '1', name: 'BACKING SODA', unit: 'KG', price: 225.0, mrp: 150.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '2', name: 'BUSH APPLE', unit: 'Nos', price: 95.0, mrp: 80.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '3', name: 'Chippu', unit: 'Nos', price: 10.0, mrp: 10.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '4', name: 'Finol Colour', unit: 'Nos', price: 35.0, mrp: 30.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '5', name: 'GOBAL POWDER PKT 10', unit: 'PKT', price: 10.0, mrp: 8.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '6', name: 'KADALAPARUBI  NICE 2RS', unit: 'Nos', price: 2.0, mrp: 1.5, stock: 100, category: 'Primary', description: ''),
    Product(id: '7', name: 'LG 100 GM POWDER', unit: 'Nos', price: 160.0, mrp: 141.5, stock: 100, category: 'Primary', description: ''),
    Product(id: '8', name: 'MATCH BOX BIG', unit: 'Nos', price: 9.42, mrp: 7.2, stock: 100, category: 'Primary', description: ''),
    Product(id: '9', name: 'Milk Maid 210gm', unit: 'Nos', price: 89.0, mrp: 75.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '10', name: 'Neru Cap', unit: 'PKT', price: 180.0, mrp: 200.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '11', name: 'Nijam Pakku 50 Paisa', unit: 'CASE', price: 600.0, mrp: 537.5, stock: 100, category: 'Primary', description: ''),
    Product(id: '12', name: 'Past 10 Rs', unit: 'Nos', price: 10.0, mrp: 8.92, stock: 100, category: 'Primary', description: ''),
    Product(id: '13', name: 'Pikel Garlic 1 Kg', unit: 'Nos', price: 145.0, mrp: 78.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '14', name: 'Risk Rs 10', unit: 'Nos', price: 10.0, mrp: 10.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '15', name: 'Rusk Powder', unit: 'KG', price: 95.0, mrp: 92.3, stock: 100, category: 'Primary', description: ''),
    Product(id: '16', name: 'Shampoo', unit: 'Nos', price: 1.0, mrp: 1.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '17', name: 'Spoon Pkt 100', unit: 'Nos', price: 20.0, mrp: 17.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '18', name: 'Sunnampu Box', unit: 'Nos', price: 4.13, mrp: 5.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '19', name: 'Tissue Paper', unit: 'Nos', price: 23.53, mrp: 16.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '20', name: 'Tooth Brush', unit: 'Nos', price: 12.0, mrp: 0.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '21', name: 'Vennila Essans', unit: 'CASE', price: 227.8, mrp: 200.0, stock: 100, category: 'Primary', description: ''),
    Product(id: '22', name: 'APPALAM 100GM', unit: 'PKT', price: 20.0, mrp: 14.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '23', name: 'APPALAM 150GM', unit: 'PKT', price: 22.83, mrp: 21.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '24', name: 'Greens Appalam 150gm', unit: 'PKT', price: 24.0, mrp: 21.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '25', name: 'Greens Appalam 200gm', unit: 'PKT', price: 35.0, mrp: 28.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '26', name: 'GRENES APPALAM 50 GR', unit: 'KG', price: 160.0, mrp: 140.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '27', name: 'ONION CUDAL TTK', unit: 'Bag', price: 1570.0, mrp: 1500.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '28', name: 'Papa Appalam 100 Gm', unit: 'CASE', price: 20.0, mrp: 14.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '29', name: 'Pappa Appalam 200 Gm', unit: 'CASE', price: 40.0, mrp: 28.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '30', name: 'Sakthi Appalam 200', unit: 'CASE', price: 45.0, mrp: 36.0, stock: 100, category: 'Appalam', description: ''),
    Product(id: '31', name: 'Cocount 1 Ltr', unit: 'Lt', price: 180.0, mrp: 170.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '32', name: 'Cocunet Oil 100ml', unit: 'PKT', price: 45.0, mrp: 40.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '33', name: 'Cocunet Oil 200ml', unit: 'PKT', price: 90.0, mrp: 70.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '34', name: 'Cocunet Oil 500  Ml', unit: 'PKT', price: 190.0, mrp: 150.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '35', name: 'Gingelly Oil 1 Ltr TM', unit: 'CASE', price: 310.0, mrp: 290.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '36', name: 'Jagathguru 1', unit: 'CASE', price: 2566.6, mrp: 2550.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '37', name: 'Jagathguru 1/2', unit: 'Nos', price: 100.0, mrp: 90.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '38', name: 'Jagathguru 15 Lt', unit: 'Nos', price: 2744.56, mrp: 2600.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '39', name: 'Jagathguru 5lt', unit: 'Nos', price: 888.88, mrp: 800.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '40', name: 'Jagathguru Tin 15 Lt', unit: 'Nos', price: 2947.5, mrp: 2250.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '41', name: 'Kadalai Nice Parufi Rs.10', unit: 'Nos', price: 7.5, mrp: 6.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '42', name: 'Kadalai Nice Parupi 5*60', unit: 'Nos', price: 220.0, mrp: 170.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '43', name: 'Kadalai Nice Paruppi 24*5', unit: 'Nos', price: 90.0, mrp: 72.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '44', name: 'Kadalai Parfi Rs 40', unit: 'Nos', price: 30.0, mrp: 20.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '45', name: 'KADALAI PARUPAI 5*24', unit: 'Nos', price: 90.48, mrp: 70.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '46', name: 'Kadalai Parupi 10rs', unit: 'Nos', price: 7.5, mrp: 6.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '47', name: 'Kadalai Parupi 250g', unit: 'Nos', price: 40.0, mrp: 35.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '48', name: 'Kadalai Parupi 60*5', unit: 'Nos', price: 203.48, mrp: 200.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '49', name: 'Kadalai Parupi Rs.20', unit: 'Nos', price: 15.0, mrp: 10.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '50', name: 'KADALAI PARUPPI (250GM)', unit: 'KG', price: 176.0, mrp: 168.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '51', name: 'Kadalai Paruppi 2*75', unit: 'Nos', price: 120.0, mrp: 120.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '52', name: 'KADALAI URADAI (250GM)', unit: 'KG', price: 180.0, mrp: 175.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '53', name: 'Kadalai Urandai  250g', unit: 'Nos', price: 45.0, mrp: 30.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '54', name: 'Kadalai Urandai 2*60', unit: 'Nos', price: 100.0, mrp: 80.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '55', name: 'Kadalai Urandai 5*10 Pkt', unit: 'Nos', price: 33.0, mrp: 25.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '56', name: 'Kadalai Urundai 2*10', unit: 'Nos', price: 14.0, mrp: 10.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '57', name: 'Kadalai Urundai 60*5', unit: 'Nos', price: 189.0, mrp: 190.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '58', name: 'Karuppu Ellu Paprupi Rs.20', unit: 'Nos', price: 15.0, mrp: 12.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '59', name: 'Karuppu Ellu Parupi 60*5', unit: 'Nos', price: 220.0, mrp: 170.0, stock: 100, category: 'Bala', description: ''),
    Product(id: '60', name: 'KARUPPU ELLU PARUPPI (250GM)', unit: 'KG', price: 173.0, mrp: 168.0, stock: 100, category: 'Bala', description: ''),
  ];

  static final List<Customer> customers = [
    Customer(id: '1', name: 'Walk-in Customer', phone: '', address: 'Local', area: 'Local', gstin: ''),
  ];
}
