-- ============================================================================
-- ERP Billing System — Supabase / PostgreSQL Initial Migration
-- Run this in: Supabase Dashboard → SQL Editor  (or `psql`)
-- Safe to run multiple times (uses IF NOT EXISTS).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Helper: keep updated_at fresh on every UPDATE
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 1. invoice_series — atomic invoice numbering per series
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoice_series (
  id             smallint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_prefix  text       NOT NULL UNIQUE,
  current_number bigint     NOT NULL DEFAULT 0,
  padding        int        NOT NULL DEFAULT 4,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS trg_invoice_series_updated ON public.invoice_series;
CREATE TRIGGER trg_invoice_series_updated
  BEFORE UPDATE ON public.invoice_series
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Seed current counters from your existing data (adjust to real max values)
INSERT INTO public.invoice_series (series_prefix, current_number, padding) VALUES
  ('INV', 32, 4)   -- max INV number already issued (INV0032)
ON CONFLICT (series_prefix) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2. products — the catalogue ("product input")
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.products (
  id          bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text           NOT NULL,
  unit        text           NOT NULL DEFAULT 'PCS',
  price       numeric(12,2)  NOT NULL DEFAULT 0,   -- sale price (no GST)
  mrp         numeric(12,2)  NOT NULL DEFAULT 0,
  stock       numeric(12,3)  NOT NULL DEFAULT 0,
  category    text           NOT NULL DEFAULT 'General',
  description text,
  barcode     text,
  is_active   boolean        NOT NULL DEFAULT true,
  created_at  timestamptz    NOT NULL DEFAULT now(),
  updated_at  timestamptz    NOT NULL DEFAULT now(),
  CONSTRAINT chk_products_price_ge_0 CHECK (price >= 0),
  CONSTRAINT chk_products_stock_ge_0 CHECK (stock >= 0)
);

CREATE INDEX IF NOT EXISTS idx_products_category   ON public.products (category);
CREATE INDEX IF NOT EXISTS idx_products_name       ON public.products (name);
CREATE INDEX IF NOT EXISTS idx_products_barcode    ON public.products (barcode);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm  ON public.products USING gin (name gin_trgm_ops);

DROP TRIGGER IF EXISTS trg_products_updated ON public.products;
CREATE TRIGGER trg_products_updated
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 3. customers — the buyer ledger
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customers (
  id            bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text          NOT NULL,
  phone         text          NOT NULL DEFAULT '',
  address       text          NOT NULL DEFAULT '',
  area          text          NOT NULL DEFAULT '',
  gstin         text          NOT NULL DEFAULT '',
  credit_limit  numeric(12,2) NOT NULL DEFAULT 0,
  balance       numeric(12,2) NOT NULL DEFAULT 0,
  is_active     boolean       NOT NULL DEFAULT true,
  created_at    timestamptz   NOT NULL DEFAULT now(),
  updated_at    timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT chk_customers_credit_ge_0 CHECK (credit_limit >= 0)
);

CREATE INDEX IF NOT EXISTS idx_customers_name  ON public.customers (name);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers (phone);
CREATE INDEX IF NOT EXISTS idx_customers_area  ON public.customers (area);

DROP TRIGGER IF EXISTS trg_customers_updated ON public.customers;
CREATE TRIGGER trg_customers_updated
  BEFORE UPDATE ON public.customers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 4. bills — the sale header ("bill output")
--    Customer name/phone are denormalised snapshots so history survives edits.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bills (
  id             uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_number    text          NOT NULL UNIQUE,
  series_prefix  text          NOT NULL DEFAULT 'INV',
  customer_id    bigint        REFERENCES public.customers(id) ON DELETE SET NULL,
  customer_name  text          NOT NULL,
  customer_phone text          NOT NULL DEFAULT '',
  payment_type   text          NOT NULL DEFAULT 'Cash',   -- Cash | Credit | UPI | Card
  sales_type     text          NOT NULL DEFAULT 'Retail', -- Retail | Wholesale | Credit
  through        text          NOT NULL DEFAULT '',        -- salesman / agent
  area           text          NOT NULL DEFAULT '',
  price_list     text          NOT NULL DEFAULT 'Retail',
  remarks        text          NOT NULL DEFAULT '',
  subtotal       numeric(12,2) NOT NULL DEFAULT 0,
  discount_total numeric(12,2) NOT NULL DEFAULT 0,
  grand_total    numeric(12,2) NOT NULL DEFAULT 0,
  total_qty      numeric(12,3) NOT NULL DEFAULT 0,
  item_count     int           NOT NULL DEFAULT 0,
  bill_date      date          NOT NULL DEFAULT CURRENT_DATE,
  status         text          NOT NULL DEFAULT 'active', -- active | voided
  created_by     uuid          REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at     timestamptz   NOT NULL DEFAULT now(),
  updated_at     timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT chk_bills_status CHECK (status IN ('active','voided'))
);

CREATE INDEX IF NOT EXISTS idx_bills_bill_date    ON public.bills (bill_date DESC);
CREATE INDEX IF NOT EXISTS idx_bills_customer     ON public.bills (customer_id);
CREATE INDEX IF NOT EXISTS idx_bills_created_at   ON public.bills (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bills_payment      ON public.bills (payment_type);

DROP TRIGGER IF EXISTS trg_bills_updated ON public.bills;
CREATE TRIGGER trg_bills_updated
  BEFORE UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 5. bill_items — one row per product line on a bill
--    Product name/unit/rate are snapshots so old bills never change.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bill_items (
  id               uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  bill_id          uuid          NOT NULL REFERENCES public.bills(id) ON DELETE CASCADE,
  line_no          int           NOT NULL DEFAULT 0,
  product_id       bigint        REFERENCES public.products(id) ON DELETE SET NULL,
  product_name     text          NOT NULL,
  unit             text          NOT NULL DEFAULT 'PCS',
  quantity         numeric(12,3) NOT NULL,
  rate             numeric(12,2) NOT NULL,
  discount_percent numeric(5,2)  NOT NULL DEFAULT 0,
  discount_amount  numeric(12,2) NOT NULL DEFAULT 0,
  gross_amount     numeric(12,2) NOT NULL DEFAULT 0,
  total            numeric(12,2) NOT NULL DEFAULT 0,
  created_at       timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bill_items_bill_id   ON public.bill_items (bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_items_product   ON public.bill_items (product_id);

-- ----------------------------------------------------------------------------
-- 6. held_bills — "Hold" feature: save a draft cart and recall it later
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.held_bills (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name text        NOT NULL DEFAULT 'Walk-in Customer',
  items         jsonb       NOT NULL DEFAULT '[]'::jsonb,
  payment_type  text        NOT NULL DEFAULT 'Cash',
  total_qty     numeric(12,3) NOT NULL DEFAULT 0,
  grand_total   numeric(12,2) NOT NULL DEFAULT 0,
  held_at       timestamptz NOT NULL DEFAULT now(),
  status        text        NOT NULL DEFAULT 'held',   -- held | recalled | discarded
  created_by    uuid        REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_held_bills_status ON public.held_bills (status);

-- ----------------------------------------------------------------------------
-- 7. audit_log — who did what, when (bill create / void / hold)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_log (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action     text        NOT NULL,
  entity     text        NOT NULL,
  entity_id  text,
  payload    jsonb,
  created_by uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_created ON public.audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity  ON public.audit_log (entity, entity_id);

-- ============================================================================
-- INVOICE NUMBERING — atomic & concurrency-safe
-- ============================================================================
CREATE OR REPLACE FUNCTION public.next_invoice_number(p_series text)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  v_num bigint;
  v_pad int;
BEGIN
  -- Atomic: row is locked until the transaction commits
  UPDATE public.invoice_series
     SET current_number = current_number + 1
   WHERE series_prefix = p_series
   RETURNING current_number, padding INTO v_num, v_pad;

  IF NOT FOUND THEN
    INSERT INTO public.invoice_series (series_prefix, current_number) VALUES (p_series, 1)
    RETURNING current_number, padding INTO v_num, v_pad;
  END IF;

  RETURN p_series || lpad(v_num::text, v_pad, '0');
END;
$$;

-- ============================================================================
-- CREATE BILL — one atomic transaction: number + header + lines + stock
-- ============================================================================
CREATE OR REPLACE FUNCTION public.create_bill(
  p_customer_id    bigint,
  p_customer_name  text,
  p_customer_phone text DEFAULT '',
  p_payment_type   text DEFAULT 'Cash',
  p_sales_type     text DEFAULT 'Retail',
  p_through        text DEFAULT '',
  p_area           text DEFAULT '',
  p_price_list     text DEFAULT 'Retail',
  p_remarks        text DEFAULT '',
  p_items          jsonb
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
  v_bill_id     uuid;
  v_bill_number text;
  v_line_no     int             := 0;
  v_subtotal    numeric(12,2)   := 0;
  v_discount    numeric(12,2)   := 0;
  v_grand_total numeric(12,2)   := 0;
  v_total_qty   numeric(12,3)   := 0;
  v_item        jsonb;
  v_product_id  bigint;
  v_qty         numeric(12,3);
  v_rate        numeric(12,2);
  v_disc_pct    numeric(5,2);
  v_gross       numeric(12,2);
  v_disc_amt    numeric(12,2);
  v_total       numeric(12,2);
BEGIN
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Bill must contain at least one item';
  END IF;

  v_bill_number := public.next_invoice_number('INV');

  INSERT INTO public.bills (bill_number, series_prefix, customer_id, customer_name,
                            customer_phone, payment_type, sales_type, through, area,
                            price_list, remarks)
  VALUES (v_bill_number, 'INV', p_customer_id, p_customer_name, p_customer_phone,
          p_payment_type, p_sales_type, p_through, p_area, p_price_list, p_remarks)
  RETURNING id INTO v_bill_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_line_no    := v_line_no + 1;
    v_product_id := COALESCE((v_item->>'product_id')::bigint, 0);
    v_qty        := COALESCE((v_item->>'quantity')::numeric, 0);
    v_rate       := COALESCE((v_item->>'rate')::numeric, 0);
    v_disc_pct   := COALESCE((v_item->>'discount_percent')::numeric, 0);

    IF v_qty <= 0 OR v_rate <= 0 THEN
      RAISE EXCEPTION 'Line %: quantity and rate must be positive', v_line_no;
    END IF;

    -- Deduct stock atomically, refuse overselling
    UPDATE public.products
       SET stock = stock - v_qty
     WHERE id = v_product_id AND stock >= v_qty;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Insufficient stock for product id %', v_product_id;
    END IF;

    v_gross    := round(v_rate * v_qty, 2);
    v_disc_amt := round(v_gross * v_disc_pct / 100, 2);
    v_total    := round(v_gross - v_disc_amt, 2);

    v_subtotal    := v_subtotal + v_gross;
    v_discount    := v_discount + v_disc_amt;
    v_grand_total := v_grand_total + v_total;
    v_total_qty   := v_total_qty + v_qty;

    INSERT INTO public.bill_items (bill_id, line_no, product_id, product_name, unit,
                                   quantity, rate, discount_percent, discount_amount,
                                   gross_amount, total)
    VALUES (v_bill_id, v_line_no, v_product_id,
            COALESCE(v_item->>'product_name', ''),
            COALESCE(v_item->>'unit', 'PCS'),
            v_qty, v_rate, v_disc_pct, v_disc_amt, v_gross, v_total);
  END LOOP;

  UPDATE public.bills
     SET subtotal = v_subtotal, discount_total = v_discount,
         grand_total = v_grand_total, total_qty = v_total_qty, item_count = v_line_no
   WHERE id = v_bill_id;

  INSERT INTO public.audit_log (action, entity, entity_id, payload)
  VALUES ('CREATE', 'bill', v_bill_number, jsonb_build_object('grand_total', v_grand_total));

  RETURN (
    SELECT to_jsonb(b) ||
           jsonb_build_object('items',
             (SELECT jsonb_agg(to_jsonb(i) ORDER BY i.line_no)
                FROM public.bill_items i WHERE i.bill_id = b.id))
      FROM public.bills b WHERE b.id = v_bill_id
  );
END;
$$;

-- ============================================================================
-- VOID BILL — restore stock, keep the record for audit
-- ============================================================================
CREATE OR REPLACE FUNCTION public.void_bill(p_bill_number text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_id uuid;
BEGIN
  SELECT id INTO v_id FROM public.bills WHERE bill_number = p_bill_number AND status = 'active';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active bill % not found', p_bill_number;
  END IF;

  -- Restore stock
  UPDATE public.products p
     SET stock = p.stock + bi.quantity
    FROM public.bill_items bi
   WHERE bi.bill_id = v_id AND bi.product_id = p.id;

  UPDATE public.bills SET status = 'voided' WHERE id = v_id;

  INSERT INTO public.audit_log (action, entity, entity_id) VALUES ('VOID', 'bill', p_bill_number);
END;
$$;

-- ============================================================================
-- REPORTING VIEWS
-- ============================================================================
CREATE OR REPLACE VIEW public.v_daily_sales AS
SELECT bill_date,
       count(*)::int                                  AS bills,
       coalesce(sum(grand_total), 0)::numeric(12,2)   AS sales,
       coalesce(sum(discount_total), 0)::numeric(12,2) AS discounts,
       coalesce(sum(total_qty), 0)::numeric(12,3)      AS qty
FROM public.bills
WHERE status = 'active'
GROUP BY bill_date
ORDER BY bill_date DESC;

CREATE OR REPLACE VIEW public.v_top_products AS
SELECT bi.product_id,
       bi.product_name,
       sum(bi.quantity)::numeric(12,3) AS qty_sold,
       sum(bi.total)::numeric(12,2)    AS revenue
FROM public.bill_items bi
JOIN public.bills b ON b.id = bi.bill_id
WHERE b.status = 'active'
GROUP BY bi.product_id, bi.product_name
ORDER BY revenue DESC;

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- Enables RLS and lets authenticated app users read/write all rows.
-- NOTE: If you call the API from the Flask backend with the SERVICE ROLE key,
--       RLS is bypassed automatically. RLS matters only when the Flutter app
--       talks to Supabase directly with the anon/user key.
-- ============================================================================
ALTER TABLE public.invoice_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_items     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.held_bills     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log      ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['invoice_series','products','customers','bills','bill_items','held_bills','audit_log']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS app_all_%s ON public.%I;', t, t);
    EXECUTE format(
      'CREATE POLICY app_all_%s ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true);',
      t, t);
  END LOOP;
END;
$$;
